# Generated by Django 4.1.1 on 2022-11-26 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piano_man', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arquivos',
            name='nome_arquivo',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
